version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data/mongo:/data/db
  nifi:
    image: apache/nifi:1.13.2
    container_name: nifi
    ports:
      - "8060:8060"
    environment:
      - NIFI_WEB_HTTP_PORT=8060
    volumes:
      - ./nifi-drivers:/opt/nifi/drivers
      - ./nifi-data:/data
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data